Certs - Add intermediate CA, CA rotation and CRL
absmach/certs pull request #17
Opened 2024-09-13 11:22 UTC by nyagamunene

# What type of PR is this?
This is a feature because it adds the following functionality: it adds intermediate CA, CA rotation and CRL.

## What does this do?
It adds intermediate CA, CA rotation and CRL for improvement of the PKI.

## Which issue(s) does this PR fix/relate to?
- Related Issue #5 
- Resolves #5 

## Have you included tests for your changes?
Yes

## Did you document any new/modified features?
No

### Notes

2024-09-17 09:09 UTC, SammyOina requested changes

2024-09-17 09:09 UTC, SammyOina commented on service.go
> +func (s *service) IssueCert(ctx context.Context, entityID, ttl string, ipAddrs []string, options SubjectOptions) (string, error) {
When issuing a certifcate ideally, the user would pass a CSR and this would be with CA to create the certificate. Also in which cases do you use root ca and in which do you use intermediate, ideally, intermediate CAs would be used to distinguish orgnaizations/ workspaces

2024-09-17 09:30 UTC, nyagamunene commented on service.go
> +func (s *service) IssueCert(ctx context.Context, entityID, ttl string, ipAddrs []string, options SubjectOptions) (string, error) {
I can add the CSR feature for the user when issuing certs. I can search on how it needs to be implemented.

2024-09-17 09:33 UTC, nyagamunene commented on service.go
> +func (s *service) IssueCert(ctx context.Context, entityID, ttl string, ipAddrs []string, options SubjectOptions) (string, error) {
From how I understood it the root CA are generally not used to sign the users certificated directly. So intermediate certs are normally used signed with root CA then they are used to issue client certificates.

2024-09-17 10:01 UTC, dborovcanin commented on service.go
> +func (s *service) IssueCert(ctx context.Context, entityID, ttl string, ipAddrs []string, options SubjectOptions) (string, error) {
Let's keep intermediate cert instead of root CA. @SammyOina Please re-review with this in mind, and @nyagamunene you can send another PR for CSR.

2024-09-19 09:28 UTC, SammyOina requested changes

2024-09-19 09:28 UTC, SammyOina commented on service.go
> +	if now.Add(30 * 24 * time.Hour).After(s.rootCA.Certificate.NotAfter) {
use constants

2024-09-19 09:28 UTC, SammyOina commented on service.go
> +	if shouldRotate == true {
```suggestion
	if shouldRotate {
```

2024-09-19 09:28 UTC, SammyOina commented on service.go
> +		if err != nil {
how long does it take intermediate ca to expire compared to root ca

2024-09-19 10:25 UTC, SammyOina commented on service.go
> +		if err != nil {
root should be long lasting than intermediate

2024-09-19 10:29 UTC, nyagamunene commented on service.go
> +		if err != nil {
Okay then let me implement that.

2024-09-24 09:08 UTC, SammyOina requested changes

2024-09-24 09:08 UTC, SammyOina commented on postgres/init.go
> +						type		   INT,
can you enumerate type

2024-09-24 11:51 UTC, SammyOina approved these changes

2024-09-25 16:15 UTC, dborovcanin approved these changes

2024-09-25 16:15 UTC, merged