Certs - Remove all magistrala dependencies
absmach/certs pull request #4
Opened 2024-08-19 15:42 UTC by nyagamunene

# What type of PR is this?
This is a refactor because it changes the following functionality because it removes Magistrala dependencies to avoid cyclic imports.

## What does this do?
It removes Magistrala dependencies and implements some of them in the repo.

## Which issue(s) does this PR fix/relate to?
- Related Issue #1 #2 
- Resolves #1 #2 

## Have you included tests for your changes?
Yes.

## Did you document any new/modified features?
No.

### Notes

2024-08-21 09:04 UTC, arvindh123 requested changes
@dborovcanin , How this certs will be working? 
Like it will be replacing only vault or it will be replacing entire certs service in Magistrala?

2024-08-21 11:47 UTC, SammyOina requested changes
import common utilities from mg to avoid code duplication

2024-08-21 11:47 UTC, SammyOina commented on .gitignore
> +coverage
```suggestion
coverage

```

2024-08-21 11:47 UTC, SammyOina commented on Makefile
> +	@unset MOCKERY_VERSION && go generate ./...
why do you need go generate, use a mockery config

2024-08-21 11:47 UTC, SammyOina commented on api/grpc/server.go
> +			(getEntityEndpoint(svc)),
why have you removed tracing

2024-08-21 11:47 UTC, SammyOina commented on api/grpc/server.go
> +			(getEntityEndpoint(svc)),
why have you removed tracing

2024-08-21 11:47 UTC, SammyOina commented on api/http/responses.go
> +}
```suggestion
}

```

2024-08-21 11:47 UTC, SammyOina commented on docker/docker-compose.yml
> +
```suggestion

```

2024-08-21 11:47 UTC, SammyOina commented on docker/ssl/ca.crt
a standalone serevice, root ca should be generated by the service itself during initialization

2024-08-21 11:47 UTC, SammyOina commented on internal/jaeger/provider.go
can you import form mg to avoid repetition

2024-08-21 11:47 UTC, SammyOina commented on internal/postgres/postgres.go
same here

2024-08-21 11:47 UTC, SammyOina commented on internal/postgres/tracing.go
same

2024-08-25 18:04 UTC, dborovcanin requested changes

2024-08-25 18:04 UTC, dborovcanin commented on pkg/apiutil/errors.go
> +// Copyright (c) Abstract Machines
Since this is a single service, we do not need `apiutil` package from monorepo, and probably there's no need for some of these errors. Remove this package and add errors that make sense to API layer (simple `errors.go` file will work).

2024-08-25 18:04 UTC, dborovcanin commented on pkg/apiutil/transport.go
> +// Copyright (c) Abstract Machines
Same, everything from `pkg/apiutil` belongs to `api` directly. Check if all of these methods are needed.

2024-08-27 11:47 UTC, dborovcanin reviewed
Please fix the Dockerfile by removing `web` leftovers:
```dockerfile
FROM golang:1.23-alpine AS builder

ARG SVC
ARG GOARCH
ARG GOARM
ARG VERSION
ARG COMMIT
ARG TIME

WORKDIR /go/src/github.com/absmach/certs

COPY . .

RUN apk update \
    && apk add make \
    && make $SVC \
    && mv build/$SVC /exe

FROM scratch

# Rrequired for billing service
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY --from=builder /exe /
ENTRYPOINT ["/exe"]
```

2024-08-27 12:04 UTC, dborovcanin approved these changes

2024-08-27 12:05 UTC, merged