NOISSUE - Add delete certs feature
absmach/certs pull request #46
Opened 2024-11-14 11:41 UTC by nyagamunene

# What type of PR is this?

## What does this do?

## Which issue(s) does this PR fix/relate to?

## Have you included tests for your changes?

## Did you document any new/modified features?

### Notes

2024-11-14 12:03 UTC, SammyOina approved these changes

2024-11-18 09:17 UTC, dborovcanin requested changes

2024-11-18 09:17 UTC, dborovcanin commented on api/http/requests.go
> +	entityID string
Use `certID` or just `id`.

2024-11-18 09:17 UTC, dborovcanin commented on certs.go
> +	RemoveCerts(ctx context.Context, entityId string) error
Use singular `RemovCert`.

2024-11-18 09:17 UTC, dborovcanin commented on certs.go
> +	RemoveCerts(ctx context.Context, entityId string) error
Also `certID` or `id`.

2024-11-18 09:17 UTC, dborovcanin commented on sdk/sdk.go
> +func (sdk mgSDK) DeleteCerts(entityID string) errors.SDKError {
Same, use singular `DeleteCert`.

2024-11-18 09:17 UTC, dborovcanin commented on service.go
> +func (s *service) RemoveCerts(ctx context.Context, entityId string) error {
Same, use singular.

2024-11-18 10:13 UTC, dborovcanin approved these changes

2024-11-18 10:13 UTC, merged