NOISSUE - Fix ocsp with sdk
absmach/certs pull request #52
Opened 2024-11-19 17:44 UTC by nyagamunene

# What type of PR is this?
This is a bug fix because it fixes the following issue: it changes how the OCSP request is created and presented while using the SDK.

## What does this do?
it changes how the OCSP request is created and presented while using the SDK.

## Which issue(s) does this PR fix/relate to?
N/A

## Have you included tests for your changes?
No

## Did you document any new/modified features?
No

### Notes

2024-11-20 08:18 UTC, SammyOina submitted a review, later dismissed

2024-11-22 11:01 UTC, dborovcanin requested changes

2024-11-22 11:01 UTC, dborovcanin commented on sdk/sdk.go
> +		ProducedAt:   &ocspResp.ProducedAt,
```suggestion
	if len(body) == emptyOCSPbody {
		return OCSPResponse{
			Status:       CertStatus(Unknown),
			SerialNumber: sn,
		}, nil
	}

	r, err := ocsp.ParseResponse(body, nil)
	if err != nil {
		return OCSPResponse{}, errors.NewSDKError(err)
	}

	resp := OCSPResponse{
		Status:       CertStatus(r.Status),
		SerialNumber: r.SerialNumber,
		Certificate:  r.Certificate.Raw,
		RevokedAt:    &r.RevokedAt,
		IssuerHash:   r.IssuerHash.String(),
		ProducedAt:   &r.ProducedAt,
	}
	
	return resp, nil
```

2024-11-22 15:28 UTC, dborovcanin approved these changes

2024-11-22 15:28 UTC, merged